# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 13:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('number', models.CharField(max_length=10, verbose_name='number')),
                ('sub_index', models.CharField(max_length=10, verbose_name='sub_index')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('zipcode', models.CharField(max_length=20, verbose_name='zipcode')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, verbose_name='rut')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_charge', models.CharField(max_length=10, verbose_name='payment_charge')),
                ('value', models.IntegerField(verbose_name='value')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('tracking_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='date_time')),
                ('dispatch_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.DispatchOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Status'),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='status',
            field=models.ManyToManyField(through='application.OrderStatus', to='application.Status'),
        ),
        migrations.AddField(
            model_name='adress',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='application.Client'),
        ),
        migrations.AddField(
            model_name='adress',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='application.Client'),
        ),
    ]
